"""
DAW Stock Plugins — Hardcoded metadata for plugins bundled with major DAWs.

Used by the chat pipeline to cross-reference web-mentioned plugins against
what the user has access to via their DAW (in addition to scanned AU/VST3).

Each entry has the same shape as relevant `plugins` table columns so it
can be formatted by the existing RAG context builder.
"""

# ── Supported DAWs (display names) ───────────────────
SUPPORTED_DAWS = [
    "Logic Pro",
    "Ableton Live 12 Suite",
    "Cubase 13 Pro",
    "Pro Tools",
    "Studio One 7",
    "FL Studio",
    "Reaper",
    "GarageBand",
]


# ── Stock plugin data ────────────────────────────────
# All entries require: name, category
# Optional: developer, subcategory, plugin_type, character, best_used_for, emulation_of

DAW_STOCK_PLUGINS: dict[str, list[dict]] = {

    "Logic Pro": [
        # EQ
        {"name": "Channel EQ", "developer": "Apple", "category": "EQ", "subcategory": "Parametric EQ",
         "plugin_type": "effect", "character": "Clean, transparent 8-band parametric",
         "best_used_for": "Everyday mixing EQ on any source"},
        {"name": "Linear Phase EQ", "developer": "Apple", "category": "EQ", "subcategory": "Linear Phase EQ",
         "plugin_type": "effect", "character": "Phase-coherent, slightly latency-heavy",
         "best_used_for": "Mastering, sensitive low-end processing"},
        {"name": "Vintage EQ Collection", "developer": "Apple", "category": "EQ", "subcategory": "Vintage EQ",
         "plugin_type": "effect", "character": "Emulations of classic console and outboard EQs",
         "emulation_of": "Pultec EQP-1A, API 560, Neve 1073",
         "best_used_for": "Adding analog color to vocals, drums, mix bus"},
        {"name": "Match EQ", "developer": "Apple", "category": "EQ", "subcategory": "Match EQ",
         "plugin_type": "effect", "character": "Matches spectral shape of reference",
         "best_used_for": "Tonal matching to references"},
        # Dynamics
        {"name": "Compressor", "developer": "Apple", "category": "Compressor", "subcategory": "Multi-model",
         "plugin_type": "effect", "character": "Seven emulated circuits (VCA, FET, Opto, Vintage FET, etc.)",
         "best_used_for": "Any compression task — versatile do-it-all"},
        {"name": "Vintage Opto", "developer": "Apple", "category": "Compressor", "subcategory": "Opto Compressor",
         "plugin_type": "effect", "character": "Smooth, musical tube opto",
         "emulation_of": "Teletronix LA-2A",
         "best_used_for": "Vocals, bass, gentle leveling"},
        {"name": "Vintage FET", "developer": "Apple", "category": "Compressor", "subcategory": "FET Compressor",
         "plugin_type": "effect", "character": "Fast, aggressive FET",
         "emulation_of": "UREI 1176",
         "best_used_for": "Vocals, drums, aggressive compression"},
        {"name": "Vintage VCA", "developer": "Apple", "category": "Compressor", "subcategory": "VCA Compressor",
         "plugin_type": "effect", "character": "Punchy VCA with glue character",
         "emulation_of": "SSL G-Series Bus Compressor",
         "best_used_for": "Mix bus, drum bus glue"},
        {"name": "Limiter", "developer": "Apple", "category": "Limiter", "subcategory": "Brickwall Limiter",
         "plugin_type": "effect", "character": "Basic brickwall peak limiter",
         "best_used_for": "Loudness maximizing on master bus"},
        {"name": "Adaptive Limiter", "developer": "Apple", "category": "Limiter", "subcategory": "Mastering Limiter",
         "plugin_type": "effect", "character": "Transparent mastering-style limiter",
         "best_used_for": "Final master loudness"},
        {"name": "Multipressor", "developer": "Apple", "category": "Multiband Dynamics", "subcategory": "Multiband Compressor",
         "plugin_type": "effect", "character": "4-band multiband dynamics",
         "best_used_for": "Mix bus control, de-essing, mastering"},
        {"name": "Noise Gate", "developer": "Apple", "category": "Gate", "subcategory": "Noise Gate",
         "plugin_type": "effect", "character": "Standard gate/expander",
         "best_used_for": "Drum cleanup, vocal breath reduction"},
        {"name": "DeEsser 2", "developer": "Apple", "category": "De-esser", "subcategory": "De-esser",
         "plugin_type": "effect", "character": "Dynamic sibilance reduction",
         "best_used_for": "Vocal sibilance control"},
        # Reverb
        {"name": "ChromaVerb", "developer": "Apple", "category": "Reverb", "subcategory": "Algorithmic Reverb",
         "plugin_type": "effect", "character": "Modern algorithmic, 14 rooms, creative",
         "best_used_for": "Vocals, drums, ambient spaces"},
        {"name": "Space Designer", "developer": "Apple", "category": "Reverb", "subcategory": "Convolution Reverb",
         "plugin_type": "effect", "character": "Convolution with built-in IR library",
         "best_used_for": "Realistic room/hall emulation"},
        {"name": "Silver Verb", "developer": "Apple", "category": "Reverb", "subcategory": "Algorithmic Reverb",
         "plugin_type": "effect", "character": "Simple, efficient algo reverb",
         "best_used_for": "Quick reverb sends, CPU-light mixes"},
        # Delay / Modulation
        {"name": "Echo", "developer": "Apple", "category": "Delay", "subcategory": "Digital Delay",
         "plugin_type": "effect", "character": "Clean tempo-synced digital delay",
         "best_used_for": "Everyday delay tasks"},
        {"name": "Delay Designer", "developer": "Apple", "category": "Delay", "subcategory": "Multi-tap Delay",
         "plugin_type": "effect", "character": "Up to 26 taps, programmable rhythms",
         "best_used_for": "Complex rhythmic delays, sound design"},
        {"name": "Tape Delay", "developer": "Apple", "category": "Delay", "subcategory": "Tape Delay",
         "plugin_type": "effect", "character": "Warm tape-style delay with wow/flutter",
         "best_used_for": "Dub-style delays, vintage vibe"},
        {"name": "Stereo Delay", "developer": "Apple", "category": "Delay", "subcategory": "Stereo Delay",
         "plugin_type": "effect", "character": "Independent L/R delay",
         "best_used_for": "Wide ping-pong delays"},
        {"name": "Chorus", "developer": "Apple", "category": "Chorus", "subcategory": "Chorus",
         "plugin_type": "effect", "character": "Classic chorus",
         "best_used_for": "Guitars, pads, width"},
        {"name": "Flanger", "developer": "Apple", "category": "Flanger", "subcategory": "Flanger",
         "plugin_type": "effect", "character": "Classic flanger",
         "best_used_for": "Guitars, special effects"},
        {"name": "Phaser", "developer": "Apple", "category": "Phaser", "subcategory": "Phaser",
         "plugin_type": "effect", "character": "Multi-stage phaser",
         "best_used_for": "Guitars, keys, motion"},
        {"name": "Modulation Delay", "developer": "Apple", "category": "Modulation", "subcategory": "Modulation Delay",
         "plugin_type": "effect", "character": "Delay with modulation",
         "best_used_for": "Chorus/flanger-style motion effects"},
        # Creative / Distortion
        {"name": "Phat FX", "developer": "Apple", "category": "Multi-FX", "subcategory": "Multi-FX Chain",
         "plugin_type": "effect", "character": "Stackable distortion/modulation/compression",
         "best_used_for": "Lo-fi character, creative processing"},
        {"name": "Pedalboard", "developer": "Apple", "category": "Multi-FX", "subcategory": "Guitar Pedal Chain",
         "plugin_type": "effect", "character": "Stompbox chain emulations",
         "best_used_for": "Guitar tones"},
        {"name": "Amp Designer", "developer": "Apple", "category": "Amp Simulator", "subcategory": "Guitar Amp",
         "plugin_type": "effect", "character": "Guitar amp/cab models",
         "best_used_for": "Guitar tones"},
        {"name": "Bass Amp Designer", "developer": "Apple", "category": "Amp Simulator", "subcategory": "Bass Amp",
         "plugin_type": "effect", "character": "Bass amp/cab models",
         "best_used_for": "Bass guitar tones"},
        {"name": "Distortion II", "developer": "Apple", "category": "Distortion", "subcategory": "Distortion",
         "plugin_type": "effect", "character": "Versatile digital distortion",
         "best_used_for": "Aggressive tones, grit"},
        {"name": "Overdrive", "developer": "Apple", "category": "Distortion", "subcategory": "Overdrive",
         "plugin_type": "effect", "character": "Tube-style soft clipping",
         "best_used_for": "Warm drive on any source"},
        {"name": "Bitcrusher", "developer": "Apple", "category": "Distortion", "subcategory": "Bitcrusher",
         "plugin_type": "effect", "character": "Bit reduction + sample rate",
         "best_used_for": "Lo-fi, glitch textures"},
        # Instruments
        {"name": "Alchemy", "developer": "Apple", "category": "Synth", "subcategory": "Hybrid Synth",
         "plugin_type": "instrument", "character": "Deep hybrid synth — sample, granular, additive, spectral",
         "best_used_for": "Cinematic, sound design, lush pads"},
        {"name": "Sculpture", "developer": "Apple", "category": "Synth", "subcategory": "Physical Modeling Synth",
         "plugin_type": "instrument", "character": "Component/string modeling",
         "best_used_for": "Unique timbres, acoustic-like textures"},
        {"name": "ES2", "developer": "Apple", "category": "Synth", "subcategory": "Hybrid Synth",
         "plugin_type": "instrument", "character": "Subtractive + FM hybrid",
         "best_used_for": "Leads, pads, basses"},
        {"name": "ES1", "developer": "Apple", "category": "Synth", "subcategory": "Subtractive Synth",
         "plugin_type": "instrument", "character": "Simple analog-style synth",
         "best_used_for": "Quick basses and leads"},
        {"name": "Retro Synth", "developer": "Apple", "category": "Synth", "subcategory": "Vintage Synth",
         "plugin_type": "instrument", "character": "Four vintage modes (analog, sync, table, FM)",
         "best_used_for": "Retro sounds"},
        {"name": "Quick Sampler", "developer": "Apple", "category": "Sampler", "subcategory": "Quick Sampler",
         "plugin_type": "instrument", "character": "Drag-and-drop sampling with slice mode",
         "best_used_for": "One-shot sampling, chops"},
        {"name": "Sampler", "developer": "Apple", "category": "Sampler", "subcategory": "Multi-sampler",
         "plugin_type": "instrument", "character": "Deep multisample instrument",
         "best_used_for": "Keyswitched multisamples, orchestral libraries"},
        {"name": "Drum Machine Designer", "developer": "Apple", "category": "Drum Machine", "subcategory": "Drum Sampler",
         "plugin_type": "instrument", "character": "Modern drum kit builder",
         "best_used_for": "Electronic drums, hip-hop kits"},
        {"name": "Drum Kit Designer", "developer": "Apple", "category": "Drum Machine", "subcategory": "Acoustic Drums",
         "plugin_type": "instrument", "character": "Producer-recorded acoustic kits",
         "best_used_for": "Realistic acoustic drums"},
        # Pitch / Tuning
        {"name": "Pitch Correction", "developer": "Apple", "category": "Pitch Correction", "subcategory": "Auto-Tune Style",
         "plugin_type": "effect", "character": "Basic real-time pitch correction",
         "best_used_for": "Vocal tuning"},
        {"name": "Flex Pitch", "developer": "Apple", "category": "Pitch Correction", "subcategory": "Note-based Pitch Editor",
         "plugin_type": "effect", "character": "Melodyne-style note editing",
         "best_used_for": "Surgical vocal tuning and timing"},
    ],

    "Ableton Live 12 Suite": [
        # EQ
        {"name": "EQ Eight", "developer": "Ableton", "category": "EQ", "subcategory": "Parametric EQ",
         "plugin_type": "effect", "character": "Clean 8-band parametric",
         "best_used_for": "Everyday mixing"},
        {"name": "EQ Three", "developer": "Ableton", "category": "EQ", "subcategory": "3-Band EQ",
         "plugin_type": "effect", "character": "DJ-style 3-band with kill switches",
         "best_used_for": "Live performance, DJ-style transitions"},
        # Dynamics
        {"name": "Glue Compressor", "developer": "Ableton", "category": "Compressor", "subcategory": "VCA Compressor",
         "plugin_type": "effect", "character": "SSL G-bus style glue",
         "emulation_of": "SSL G-Series Bus Compressor",
         "best_used_for": "Mix bus, drum bus glue"},
        {"name": "Compressor", "developer": "Ableton", "category": "Compressor", "subcategory": "Multi-mode",
         "plugin_type": "effect", "character": "Clean feed-forward/feedback modes",
         "best_used_for": "General compression"},
        {"name": "Multiband Dynamics", "developer": "Ableton", "category": "Multiband Dynamics", "subcategory": "Multiband Compressor",
         "plugin_type": "effect", "character": "3-band upward/downward compression/expansion",
         "best_used_for": "Mastering, mix bus, vocal polish"},
        {"name": "Limiter", "developer": "Ableton", "category": "Limiter", "subcategory": "Brickwall Limiter",
         "plugin_type": "effect", "character": "Transparent peak limiter",
         "best_used_for": "Master bus loudness"},
        {"name": "Gate", "developer": "Ableton", "category": "Gate", "subcategory": "Noise Gate",
         "plugin_type": "effect", "character": "Standard gate",
         "best_used_for": "Drum cleanup"},
        # Saturation / Distortion
        {"name": "Saturator", "developer": "Ableton", "category": "Saturation", "subcategory": "Waveshaper",
         "plugin_type": "effect", "character": "Multiple saturation curves",
         "best_used_for": "Analog-style warmth, harmonic enhancement"},
        {"name": "Drive", "developer": "Ableton", "category": "Distortion", "subcategory": "Analog Drive",
         "plugin_type": "effect", "character": "Analog-modeled drive with tone",
         "best_used_for": "Drums, bass, character"},
        {"name": "Roar", "developer": "Ableton", "category": "Distortion", "subcategory": "Multiband Saturation",
         "plugin_type": "effect", "character": "Modern multiband distortion/saturation (Live 12)",
         "best_used_for": "Aggressive tones, sound design"},
        {"name": "Pedal", "developer": "Ableton", "category": "Distortion", "subcategory": "Guitar Pedal",
         "plugin_type": "effect", "character": "Overdrive/distortion/fuzz stompbox",
         "best_used_for": "Guitar tones"},
        {"name": "Amp", "developer": "Ableton", "category": "Amp Simulator", "subcategory": "Guitar Amp",
         "plugin_type": "effect", "character": "7 classic amp models",
         "best_used_for": "Guitar tones"},
        {"name": "Cabinet", "developer": "Ableton", "category": "Amp Simulator", "subcategory": "Cabinet IR",
         "plugin_type": "effect", "character": "Cab emulation, usually paired with Amp",
         "best_used_for": "Guitar cabinet coloring"},
        # Reverb / Delay
        {"name": "Hybrid Reverb", "developer": "Ableton", "category": "Reverb", "subcategory": "Convolution + Algo Reverb",
         "plugin_type": "effect", "character": "Convolution IR + algorithmic tail",
         "best_used_for": "Realistic spaces + creative tails"},
        {"name": "Reverb", "developer": "Ableton", "category": "Reverb", "subcategory": "Algorithmic Reverb",
         "plugin_type": "effect", "character": "Classic algorithmic reverb",
         "best_used_for": "Everyday reverb tasks"},
        {"name": "Echo", "developer": "Ableton", "category": "Delay", "subcategory": "Analog/Digital Delay",
         "plugin_type": "effect", "character": "Deep delay with character modes",
         "best_used_for": "Dub-style, analog-flavored delays"},
        {"name": "Delay", "developer": "Ableton", "category": "Delay", "subcategory": "Simple Delay",
         "plugin_type": "effect", "character": "Straightforward tempo delay",
         "best_used_for": "Basic rhythmic delay"},
        # Modulation
        {"name": "Chorus-Ensemble", "developer": "Ableton", "category": "Chorus", "subcategory": "Chorus/Ensemble",
         "plugin_type": "effect", "character": "Chorus with ensemble mode",
         "best_used_for": "Width, pads, keys"},
        {"name": "Phaser-Flanger", "developer": "Ableton", "category": "Phaser", "subcategory": "Phaser/Flanger",
         "plugin_type": "effect", "character": "Combined phaser + flanger",
         "best_used_for": "Guitars, motion"},
        {"name": "Auto Filter", "developer": "Ableton", "category": "Filter", "subcategory": "Resonant Filter",
         "plugin_type": "effect", "character": "LFO/envelope modulated filter",
         "best_used_for": "Filter sweeps, rhythmic filter effects"},
        {"name": "Auto Pan", "developer": "Ableton", "category": "Modulation", "subcategory": "Tremolo/Pan",
         "plugin_type": "effect", "character": "LFO panner/tremolo",
         "best_used_for": "Rhythmic panning, tremolo"},
        {"name": "Beat Repeat", "developer": "Ableton", "category": "Glitch/Slicer", "subcategory": "Beat Repeater",
         "plugin_type": "effect", "character": "Stutter/repeat grid effect",
         "best_used_for": "Glitchy fills, transitions"},
        {"name": "Vocoder", "developer": "Ableton", "category": "Vocoder", "subcategory": "Vocoder",
         "plugin_type": "effect", "character": "Classic vocoder",
         "best_used_for": "Robot voices, talking synths"},
        # Instruments
        {"name": "Operator", "developer": "Ableton", "category": "Synth", "subcategory": "FM Synth",
         "plugin_type": "instrument", "character": "4-operator FM synth with subtractive feel",
         "best_used_for": "Basses, leads, keys, hybrid sounds"},
        {"name": "Wavetable", "developer": "Ableton", "category": "Synth", "subcategory": "Wavetable Synth",
         "plugin_type": "instrument", "character": "Modern wavetable synth",
         "best_used_for": "Evolving pads, modern basses, EDM leads"},
        {"name": "Drift", "developer": "Ableton", "category": "Synth", "subcategory": "Analog Synth",
         "plugin_type": "instrument", "character": "Analog-style 2-oscillator synth (Live 12)",
         "best_used_for": "Classic analog basses and leads"},
        {"name": "Analog", "developer": "Ableton", "category": "Synth", "subcategory": "Analog Synth",
         "plugin_type": "instrument", "character": "Virtual analog subtractive",
         "best_used_for": "Classic subtractive sounds"},
        {"name": "Meld", "developer": "Ableton", "category": "Synth", "subcategory": "Bi-timbral Synth",
         "plugin_type": "instrument", "character": "MPE-first dual-voice synth (Live 12)",
         "best_used_for": "Expressive MPE performance"},
        {"name": "Simpler", "developer": "Ableton", "category": "Sampler", "subcategory": "Simple Sampler",
         "plugin_type": "instrument", "character": "One-shot/slice sampler",
         "best_used_for": "Chops, slice-based drum kits"},
        {"name": "Sampler", "developer": "Ableton", "category": "Sampler", "subcategory": "Multi-sampler",
         "plugin_type": "instrument", "character": "Full multisample instrument",
         "best_used_for": "Multi-zone instruments, complex sampled sounds"},
        {"name": "Granulator III", "developer": "Ableton", "category": "Sampler", "subcategory": "Granular Sampler",
         "plugin_type": "instrument", "character": "Granular synthesis (Live 12)",
         "best_used_for": "Textures, ambient, sound design"},
        {"name": "Drum Rack", "developer": "Ableton", "category": "Drum Machine", "subcategory": "Drum Rack",
         "plugin_type": "instrument", "character": "Drum kit container for Simplers and external plugins",
         "best_used_for": "Beat programming, drum kit routing"},
        # Utility / Analysis
        {"name": "Spectrum", "developer": "Ableton", "category": "Analyzer", "subcategory": "Spectrum Analyzer",
         "plugin_type": "effect", "character": "Real-time spectrum analyzer",
         "best_used_for": "Visual analysis during mixing"},
        {"name": "Tuner", "developer": "Ableton", "category": "Analyzer", "subcategory": "Tuner",
         "plugin_type": "effect", "character": "Pitch tuner",
         "best_used_for": "Tuning instruments"},
        {"name": "Utility", "developer": "Ableton", "category": "Utility", "subcategory": "Gain/Pan Utility",
         "plugin_type": "effect", "character": "Gain, pan, mid/side, mute",
         "best_used_for": "Level management, M/S tricks"},
    ],

    "Cubase 13 Pro": [
        # EQ
        {"name": "Frequency 2", "developer": "Steinberg", "category": "EQ", "subcategory": "Dynamic EQ",
         "plugin_type": "effect", "character": "8-band parametric + dynamic mode + M/S per band",
         "best_used_for": "Modern mixing, dynamic EQ tasks"},
        {"name": "StudioEQ", "developer": "Steinberg", "category": "EQ", "subcategory": "Parametric EQ",
         "plugin_type": "effect", "character": "Clean 4-band parametric",
         "best_used_for": "Standard mixing EQ"},
        {"name": "VST Classic EQ", "developer": "Steinberg", "category": "EQ", "subcategory": "Vintage EQ",
         "plugin_type": "effect", "character": "Vintage-style 4-band",
         "best_used_for": "Analog-flavored tone shaping"},
        # Dynamics
        {"name": "VintageCompressor", "developer": "Steinberg", "category": "Compressor", "subcategory": "Vintage Compressor",
         "plugin_type": "effect", "character": "70s-style analog compressor",
         "best_used_for": "Drums, bass, vintage character"},
        {"name": "TubeCompressor", "developer": "Steinberg", "category": "Compressor", "subcategory": "Tube Compressor",
         "plugin_type": "effect", "character": "Warm tube-style compression",
         "best_used_for": "Vocals, bus processing"},
        {"name": "Compressor", "developer": "Steinberg", "category": "Compressor", "subcategory": "Clean Compressor",
         "plugin_type": "effect", "character": "Clean modern compressor",
         "best_used_for": "General compression"},
        {"name": "MultibandCompressor", "developer": "Steinberg", "category": "Multiband Dynamics", "subcategory": "Multiband Compressor",
         "plugin_type": "effect", "character": "4-band multiband",
         "best_used_for": "Mix bus, mastering"},
        {"name": "VoxComp", "developer": "Steinberg", "category": "Compressor", "subcategory": "Vocal Compressor",
         "plugin_type": "effect", "character": "Optimized for vocals",
         "best_used_for": "Lead vocals"},
        {"name": "Maximizer", "developer": "Steinberg", "category": "Limiter", "subcategory": "Mastering Limiter",
         "plugin_type": "effect", "character": "Loudness maximizer",
         "best_used_for": "Master bus loudness"},
        {"name": "Brickwall Limiter", "developer": "Steinberg", "category": "Limiter", "subcategory": "Brickwall Limiter",
         "plugin_type": "effect", "character": "True-peak brickwall",
         "best_used_for": "Final master limiting"},
        {"name": "DeEsser", "developer": "Steinberg", "category": "De-esser", "subcategory": "De-esser",
         "plugin_type": "effect", "character": "Broadband/split-band de-essing",
         "best_used_for": "Vocal sibilance"},
        {"name": "Gate", "developer": "Steinberg", "category": "Gate", "subcategory": "Noise Gate",
         "plugin_type": "effect", "character": "Standard gate",
         "best_used_for": "Drum cleanup"},
        # Reverb
        {"name": "REVerence", "developer": "Steinberg", "category": "Reverb", "subcategory": "Convolution Reverb",
         "plugin_type": "effect", "character": "Convolution with extensive IR library",
         "best_used_for": "Realistic spaces"},
        {"name": "RoomWorks", "developer": "Steinberg", "category": "Reverb", "subcategory": "Algorithmic Reverb",
         "plugin_type": "effect", "character": "CPU-flexible algorithmic reverb",
         "best_used_for": "Everyday reverb"},
        {"name": "REVelation", "developer": "Steinberg", "category": "Reverb", "subcategory": "Algorithmic Reverb",
         "plugin_type": "effect", "character": "Modern algo reverb",
         "best_used_for": "Clean modern reverbs"},
        # Delay / Modulation
        {"name": "PingPongDelay", "developer": "Steinberg", "category": "Delay", "subcategory": "Stereo Delay",
         "plugin_type": "effect", "character": "Ping-pong delay",
         "best_used_for": "Stereo rhythmic delays"},
        {"name": "MonoDelay", "developer": "Steinberg", "category": "Delay", "subcategory": "Mono Delay",
         "plugin_type": "effect", "character": "Mono tempo delay",
         "best_used_for": "Basic rhythmic delay"},
        {"name": "StereoDelay", "developer": "Steinberg", "category": "Delay", "subcategory": "Stereo Delay",
         "plugin_type": "effect", "character": "Independent L/R delay",
         "best_used_for": "Wide delay effects"},
        {"name": "Chorus", "developer": "Steinberg", "category": "Chorus", "subcategory": "Chorus",
         "plugin_type": "effect", "character": "Classic chorus",
         "best_used_for": "Width, thickening"},
        {"name": "Flanger", "developer": "Steinberg", "category": "Flanger", "subcategory": "Flanger",
         "plugin_type": "effect", "character": "Classic flanger",
         "best_used_for": "Creative effects"},
        {"name": "Phaser", "developer": "Steinberg", "category": "Phaser", "subcategory": "Phaser",
         "plugin_type": "effect", "character": "Multi-stage phaser",
         "best_used_for": "Motion effects"},
        # Saturation / Distortion
        {"name": "MagnetoII", "developer": "Steinberg", "category": "Saturation", "subcategory": "Tape Saturation",
         "plugin_type": "effect", "character": "Tape machine emulation",
         "best_used_for": "Warmth, glue, tape color"},
        {"name": "Quadrafuzz v2", "developer": "Steinberg", "category": "Distortion", "subcategory": "Multiband Distortion",
         "plugin_type": "effect", "character": "4-band distortion/saturation",
         "best_used_for": "Bass enhancement, creative distortion"},
        {"name": "AmpSimulator", "developer": "Steinberg", "category": "Amp Simulator", "subcategory": "Guitar Amp",
         "plugin_type": "effect", "character": "Guitar amp modeler",
         "best_used_for": "Guitar tones"},
        {"name": "DaTube", "developer": "Steinberg", "category": "Saturation", "subcategory": "Tube Saturation",
         "plugin_type": "effect", "character": "Tube warmth",
         "best_used_for": "Analog-style thickness"},
        # Pitch
        {"name": "PitchCorrect", "developer": "Steinberg", "category": "Pitch Correction", "subcategory": "Auto-Tune Style",
         "plugin_type": "effect", "character": "Real-time pitch correction",
         "best_used_for": "Vocal tuning"},
        {"name": "VariAudio", "developer": "Steinberg", "category": "Pitch Correction", "subcategory": "Note-based Pitch Editor",
         "plugin_type": "effect", "character": "Melodyne-style in-DAW editing",
         "best_used_for": "Detailed vocal tuning"},
        # Instruments
        {"name": "HALion Sonic", "developer": "Steinberg", "category": "Sampler", "subcategory": "Workstation",
         "plugin_type": "instrument", "character": "Full multitimbral workstation (sample + synth)",
         "best_used_for": "Everyday instrument sounds"},
        {"name": "Groove Agent SE", "developer": "Steinberg", "category": "Drum Machine", "subcategory": "Drum Sampler",
         "plugin_type": "instrument", "character": "Pattern-based drum module",
         "best_used_for": "Drum tracks, beat building"},
        {"name": "Retrologue", "developer": "Steinberg", "category": "Synth", "subcategory": "Analog Synth",
         "plugin_type": "instrument", "character": "Virtual analog synth",
         "best_used_for": "Classic analog sounds"},
        {"name": "Padshop", "developer": "Steinberg", "category": "Synth", "subcategory": "Granular Synth",
         "plugin_type": "instrument", "character": "Granular + spectral",
         "best_used_for": "Pads, textures"},
        {"name": "Backbone", "developer": "Steinberg", "category": "Drum Machine", "subcategory": "Drum Designer",
         "plugin_type": "instrument", "character": "Layered drum designer",
         "best_used_for": "Custom drum sounds"},
        {"name": "Mystic", "developer": "Steinberg", "category": "Synth", "subcategory": "Physical Modeling Synth",
         "plugin_type": "instrument", "character": "Spectral/resonator synth",
         "best_used_for": "Unusual tones"},
    ],

    "Pro Tools": [
        {"name": "EQ3 7-Band", "developer": "Avid", "category": "EQ", "subcategory": "Parametric EQ",
         "plugin_type": "effect", "character": "Clean 7-band parametric",
         "best_used_for": "Standard mixing EQ"},
        {"name": "EQ3 1-Band", "developer": "Avid", "category": "EQ", "subcategory": "Single-band EQ",
         "plugin_type": "effect", "character": "Single-band surgical EQ",
         "best_used_for": "Surgical cuts"},
        {"name": "Dyn3 Compressor/Limiter", "developer": "Avid", "category": "Compressor", "subcategory": "Clean Compressor",
         "plugin_type": "effect", "character": "Clean flexible compressor",
         "best_used_for": "General compression"},
        {"name": "Dyn3 Expander/Gate", "developer": "Avid", "category": "Gate", "subcategory": "Expander/Gate",
         "plugin_type": "effect", "character": "Combined gate/expander",
         "best_used_for": "Drum cleanup"},
        {"name": "Dyn3 De-Esser", "developer": "Avid", "category": "De-esser", "subcategory": "De-esser",
         "plugin_type": "effect", "character": "Sibilance reduction",
         "best_used_for": "Vocals"},
        {"name": "BF-76", "developer": "Avid", "category": "Compressor", "subcategory": "FET Compressor",
         "plugin_type": "effect", "character": "FET 1176-style",
         "emulation_of": "UREI 1176",
         "best_used_for": "Vocals, drums, aggressive compression"},
        {"name": "BF-2A", "developer": "Avid", "category": "Compressor", "subcategory": "Opto Compressor",
         "plugin_type": "effect", "character": "Tube opto LA-2A style",
         "emulation_of": "Teletronix LA-2A",
         "best_used_for": "Vocals, bass, smooth leveling"},
        {"name": "D-Verb", "developer": "Avid", "category": "Reverb", "subcategory": "Algorithmic Reverb",
         "plugin_type": "effect", "character": "Classic Pro Tools algorithmic reverb",
         "best_used_for": "Everyday reverb"},
        {"name": "ReVibe II", "developer": "Avid", "category": "Reverb", "subcategory": "Algorithmic Reverb",
         "plugin_type": "effect", "character": "Modern algorithmic reverb",
         "best_used_for": "Vocals, drums, polished spaces"},
        {"name": "Air Reverb", "developer": "Avid", "category": "Reverb", "subcategory": "Algorithmic Reverb",
         "plugin_type": "effect", "character": "Plate/room/hall modes",
         "best_used_for": "Quick reverb tasks"},
        {"name": "Maxim", "developer": "Avid", "category": "Limiter", "subcategory": "Brickwall Limiter",
         "plugin_type": "effect", "character": "Peak limiter",
         "best_used_for": "Mastering loudness"},
        {"name": "Pro Compressor", "developer": "Avid", "category": "Compressor", "subcategory": "Mastering Compressor",
         "plugin_type": "effect", "character": "Multi-stage mastering-grade compressor",
         "best_used_for": "Mastering, mix bus"},
        {"name": "Pro Limiter", "developer": "Avid", "category": "Limiter", "subcategory": "Mastering Limiter",
         "plugin_type": "effect", "character": "Transparent true-peak limiter",
         "best_used_for": "Master bus"},
        {"name": "Pro Multiband Dynamics", "developer": "Avid", "category": "Multiband Dynamics", "subcategory": "Multiband Compressor",
         "plugin_type": "effect", "character": "4-band dynamics",
         "best_used_for": "Mastering, mix bus"},
        {"name": "Mod Delay III", "developer": "Avid", "category": "Delay", "subcategory": "Modulated Delay",
         "plugin_type": "effect", "character": "Classic Pro Tools delay with modulation",
         "best_used_for": "Rhythmic/modulated delays"},
        {"name": "Air Chorus", "developer": "Avid", "category": "Chorus", "subcategory": "Chorus",
         "plugin_type": "effect", "character": "Stereo chorus",
         "best_used_for": "Guitars, keys, width"},
        {"name": "Air Flanger", "developer": "Avid", "category": "Flanger", "subcategory": "Flanger",
         "plugin_type": "effect", "character": "Classic flanger",
         "best_used_for": "Creative effects"},
        {"name": "Air Phaser", "developer": "Avid", "category": "Phaser", "subcategory": "Phaser",
         "plugin_type": "effect", "character": "Multi-stage phaser",
         "best_used_for": "Motion effects"},
        {"name": "Air Lo-Fi", "developer": "Avid", "category": "Distortion", "subcategory": "Bitcrusher/Sample Rate",
         "plugin_type": "effect", "character": "Sample-rate/bit reduction",
         "best_used_for": "Lo-fi textures"},
        {"name": "Air Distortion", "developer": "Avid", "category": "Distortion", "subcategory": "Distortion",
         "plugin_type": "effect", "character": "Versatile digital distortion",
         "best_used_for": "Aggressive tones"},
        {"name": "Air Kill EQ", "developer": "Avid", "category": "EQ", "subcategory": "DJ-style EQ",
         "plugin_type": "effect", "character": "3-band with kill switches",
         "best_used_for": "Live performance effects"},
        {"name": "Vacuum", "developer": "Avid", "category": "Synth", "subcategory": "Analog Synth",
         "plugin_type": "instrument", "character": "Virtual analog tube synth",
         "best_used_for": "Vintage analog tones"},
        {"name": "Xpand!2", "developer": "Avid", "category": "Sampler", "subcategory": "Workstation",
         "plugin_type": "instrument", "character": "General-purpose sample workstation",
         "best_used_for": "Everyday instrument sounds"},
        {"name": "Structure", "developer": "Avid", "category": "Sampler", "subcategory": "Multi-sampler",
         "plugin_type": "instrument", "character": "Full multisample instrument",
         "best_used_for": "Sampled orchestral, ethnic, etc."},
        {"name": "Boom", "developer": "Avid", "category": "Drum Machine", "subcategory": "Drum Machine",
         "plugin_type": "instrument", "character": "Pattern-based drum machine",
         "best_used_for": "Electronic beats"},
    ],

    "Studio One 7": [
        {"name": "Pro EQ3", "developer": "PreSonus", "category": "EQ", "subcategory": "Parametric EQ",
         "plugin_type": "effect", "character": "Clean 7-band parametric with dynamic mode",
         "best_used_for": "Modern mixing"},
        {"name": "Channel Strip", "developer": "PreSonus", "category": "Channel Strip", "subcategory": "Channel Strip",
         "plugin_type": "effect", "character": "Basic EQ + compressor + gate",
         "best_used_for": "Quick per-track processing"},
        {"name": "Fat Channel XT", "developer": "PreSonus", "category": "Channel Strip", "subcategory": "Channel Strip",
         "plugin_type": "effect", "character": "Swappable compressor/EQ models",
         "best_used_for": "Flexible channel strip processing"},
        {"name": "Compressor", "developer": "PreSonus", "category": "Compressor", "subcategory": "Clean Compressor",
         "plugin_type": "effect", "character": "Clean modern compressor",
         "best_used_for": "General compression"},
        {"name": "Tricomp", "developer": "PreSonus", "category": "Compressor", "subcategory": "Multiband Compressor",
         "plugin_type": "effect", "character": "3-band compressor",
         "best_used_for": "Mastering, bus glue"},
        {"name": "Multiband Dynamics", "developer": "PreSonus", "category": "Multiband Dynamics", "subcategory": "Multiband Compressor",
         "plugin_type": "effect", "character": "5-band dynamics",
         "best_used_for": "Mix bus, mastering"},
        {"name": "Limiter 2", "developer": "PreSonus", "category": "Limiter", "subcategory": "Brickwall Limiter",
         "plugin_type": "effect", "character": "Modern true-peak limiter",
         "best_used_for": "Master bus loudness"},
        {"name": "Expander", "developer": "PreSonus", "category": "Gate", "subcategory": "Expander/Gate",
         "plugin_type": "effect", "character": "Gate/expander",
         "best_used_for": "Drum cleanup"},
        {"name": "De-Esser", "developer": "PreSonus", "category": "De-esser", "subcategory": "De-esser",
         "plugin_type": "effect", "character": "Sibilance reduction",
         "best_used_for": "Vocals"},
        {"name": "OpenAir 2", "developer": "PreSonus", "category": "Reverb", "subcategory": "Convolution Reverb",
         "plugin_type": "effect", "character": "Convolution reverb with IR library",
         "best_used_for": "Realistic spaces"},
        {"name": "Room Reverb", "developer": "PreSonus", "category": "Reverb", "subcategory": "Algorithmic Reverb",
         "plugin_type": "effect", "character": "Algorithmic reverb",
         "best_used_for": "Everyday reverb"},
        {"name": "Mixverb", "developer": "PreSonus", "category": "Reverb", "subcategory": "Algorithmic Reverb",
         "plugin_type": "effect", "character": "Quick, CPU-light reverb",
         "best_used_for": "Send reverb in dense mixes"},
        {"name": "Analog Delay", "developer": "PreSonus", "category": "Delay", "subcategory": "Analog Delay",
         "plugin_type": "effect", "character": "BBD-style analog delay",
         "best_used_for": "Warm analog-flavored delays"},
        {"name": "Beat Delay", "developer": "PreSonus", "category": "Delay", "subcategory": "Digital Delay",
         "plugin_type": "effect", "character": "Tempo-synced digital delay",
         "best_used_for": "Rhythmic delays"},
        {"name": "Groove Delay", "developer": "PreSonus", "category": "Delay", "subcategory": "Multi-tap Delay",
         "plugin_type": "effect", "character": "Groove-based multi-tap delay",
         "best_used_for": "Rhythmic patterns"},
        {"name": "Ampire", "developer": "PreSonus", "category": "Amp Simulator", "subcategory": "Guitar Amp",
         "plugin_type": "effect", "character": "Guitar amp/cab/effects",
         "best_used_for": "Guitar tones"},
        {"name": "Redlight Dist", "developer": "PreSonus", "category": "Distortion", "subcategory": "Distortion",
         "plugin_type": "effect", "character": "Versatile distortion",
         "best_used_for": "Creative distortion"},
        {"name": "Chorus", "developer": "PreSonus", "category": "Chorus", "subcategory": "Chorus",
         "plugin_type": "effect", "character": "Stereo chorus",
         "best_used_for": "Width effects"},
        {"name": "Flange", "developer": "PreSonus", "category": "Flanger", "subcategory": "Flanger",
         "plugin_type": "effect", "character": "Classic flanger",
         "best_used_for": "Motion effects"},
        {"name": "Phaser", "developer": "PreSonus", "category": "Phaser", "subcategory": "Phaser",
         "plugin_type": "effect", "character": "Stereo phaser",
         "best_used_for": "Motion effects"},
        {"name": "Binaural Pan", "developer": "PreSonus", "category": "Utility", "subcategory": "Panner",
         "plugin_type": "effect", "character": "Binaural panner",
         "best_used_for": "Spatial audio, headphone mixing"},
        {"name": "Mai Tai", "developer": "PreSonus", "category": "Synth", "subcategory": "Analog Synth",
         "plugin_type": "instrument", "character": "Polyphonic analog-modeling synth",
         "best_used_for": "Classic analog sounds"},
        {"name": "Presence XT", "developer": "PreSonus", "category": "Sampler", "subcategory": "Workstation",
         "plugin_type": "instrument", "character": "Multisample workstation",
         "best_used_for": "Everyday instrument sounds"},
        {"name": "Impact XT", "developer": "PreSonus", "category": "Drum Machine", "subcategory": "Drum Sampler",
         "plugin_type": "instrument", "character": "Pattern-based drum sampler",
         "best_used_for": "Beat production"},
        {"name": "SampleOne XT", "developer": "PreSonus", "category": "Sampler", "subcategory": "Multi-sampler",
         "plugin_type": "instrument", "character": "Full multi-sample instrument",
         "best_used_for": "Custom sampled instruments"},
    ],

    "FL Studio": [
        {"name": "Fruity Parametric EQ 2", "developer": "Image-Line", "category": "EQ", "subcategory": "Parametric EQ",
         "plugin_type": "effect", "character": "Clean 7-band parametric",
         "best_used_for": "Everyday mixing"},
        {"name": "Fruity Compressor", "developer": "Image-Line", "category": "Compressor", "subcategory": "Clean Compressor",
         "plugin_type": "effect", "character": "Simple compressor",
         "best_used_for": "General compression"},
        {"name": "Fruity Multiband Compressor", "developer": "Image-Line", "category": "Multiband Dynamics", "subcategory": "Multiband Compressor",
         "plugin_type": "effect", "character": "3-band multiband",
         "best_used_for": "Mix bus, mastering"},
        {"name": "Maximus", "developer": "Image-Line", "category": "Multiband Dynamics", "subcategory": "Mastering Processor",
         "plugin_type": "effect", "character": "5-band maximizer/compressor/limiter",
         "best_used_for": "Mastering, mix bus loudness"},
        {"name": "Fruity Limiter", "developer": "Image-Line", "category": "Limiter", "subcategory": "Brickwall Limiter",
         "plugin_type": "effect", "character": "Limiter + compressor combo",
         "best_used_for": "Master bus"},
        {"name": "Soft Clipper", "developer": "Image-Line", "category": "Distortion", "subcategory": "Soft Clipper",
         "plugin_type": "effect", "character": "Soft-clipping peak control",
         "best_used_for": "Transparent peak taming"},
        {"name": "Fruity Reverb 2", "developer": "Image-Line", "category": "Reverb", "subcategory": "Algorithmic Reverb",
         "plugin_type": "effect", "character": "Algorithmic reverb",
         "best_used_for": "Everyday reverb"},
        {"name": "Fruity Convolver", "developer": "Image-Line", "category": "Reverb", "subcategory": "Convolution Reverb",
         "plugin_type": "effect", "character": "Convolution engine with IR library",
         "best_used_for": "Realistic spaces, IR-based effects"},
        {"name": "Fruity Delay 3", "developer": "Image-Line", "category": "Delay", "subcategory": "Digital Delay",
         "plugin_type": "effect", "character": "Tempo delay with filtering",
         "best_used_for": "Standard delay tasks"},
        {"name": "Fruity Delay Bank", "developer": "Image-Line", "category": "Delay", "subcategory": "Multi-tap Delay",
         "plugin_type": "effect", "character": "8-delay multi-tap bank",
         "best_used_for": "Complex delay structures"},
        {"name": "Fruity Chorus", "developer": "Image-Line", "category": "Chorus", "subcategory": "Chorus",
         "plugin_type": "effect", "character": "Standard chorus",
         "best_used_for": "Width and thickening"},
        {"name": "Fruity Flanger", "developer": "Image-Line", "category": "Flanger", "subcategory": "Flanger",
         "plugin_type": "effect", "character": "Classic flanger",
         "best_used_for": "Creative effects"},
        {"name": "Fruity Phaser", "developer": "Image-Line", "category": "Phaser", "subcategory": "Phaser",
         "plugin_type": "effect", "character": "Multi-stage phaser",
         "best_used_for": "Motion effects"},
        {"name": "Fruity Fast Dist", "developer": "Image-Line", "category": "Distortion", "subcategory": "Distortion",
         "plugin_type": "effect", "character": "Basic distortion",
         "best_used_for": "Quick grit"},
        {"name": "Fruity Waveshaper", "developer": "Image-Line", "category": "Distortion", "subcategory": "Waveshaper",
         "plugin_type": "effect", "character": "Graphical waveshaper",
         "best_used_for": "Custom distortion curves"},
        {"name": "Pitcher", "developer": "Image-Line", "category": "Pitch Correction", "subcategory": "Auto-Tune Style",
         "plugin_type": "effect", "character": "Real-time pitch correction",
         "best_used_for": "Vocal tuning"},
        {"name": "NewTone", "developer": "Image-Line", "category": "Pitch Correction", "subcategory": "Note-based Pitch Editor",
         "plugin_type": "effect", "character": "Melodyne-style editor",
         "best_used_for": "Detailed vocal tuning"},
        {"name": "Harmor", "developer": "Image-Line", "category": "Synth", "subcategory": "Additive Synth",
         "plugin_type": "instrument", "character": "Deep additive/subtractive hybrid",
         "best_used_for": "Evolving pads, leads, sound design"},
        {"name": "Sytrus", "developer": "Image-Line", "category": "Synth", "subcategory": "FM Synth",
         "plugin_type": "instrument", "character": "Hybrid FM/RM/subtractive synth",
         "best_used_for": "Leads, basses, complex sounds"},
        {"name": "FLEX", "developer": "Image-Line", "category": "Sampler", "subcategory": "Workstation",
         "plugin_type": "instrument", "character": "Sample-based workstation",
         "best_used_for": "Everyday sounds, presets"},
        {"name": "FPC", "developer": "Image-Line", "category": "Drum Machine", "subcategory": "Drum Pad",
         "plugin_type": "instrument", "character": "MPC-style drum pad",
         "best_used_for": "Beat production"},
        {"name": "Fruity Slicer", "developer": "Image-Line", "category": "Sampler", "subcategory": "Beat Slicer",
         "plugin_type": "instrument", "character": "Beat slicing",
         "best_used_for": "Chops, drum loops"},
        {"name": "Fruity DrumSynth Live", "developer": "Image-Line", "category": "Drum Machine", "subcategory": "Drum Synth",
         "plugin_type": "instrument", "character": "Synthesized drum sounds",
         "best_used_for": "Electronic drums"},
        {"name": "FL Keys", "developer": "Image-Line", "category": "Sampler", "subcategory": "Acoustic Piano",
         "plugin_type": "instrument", "character": "Acoustic piano",
         "best_used_for": "Piano parts"},
    ],

    "Reaper": [
        {"name": "ReaEQ", "developer": "Cockos", "category": "EQ", "subcategory": "Parametric EQ",
         "plugin_type": "effect", "character": "Clean, unlimited-band parametric",
         "best_used_for": "Everyday mixing"},
        {"name": "ReaComp", "developer": "Cockos", "category": "Compressor", "subcategory": "Clean Compressor",
         "plugin_type": "effect", "character": "Clean general-purpose compressor",
         "best_used_for": "General compression"},
        {"name": "ReaXcomp", "developer": "Cockos", "category": "Multiband Dynamics", "subcategory": "Multiband Compressor",
         "plugin_type": "effect", "character": "Unlimited-band multiband compressor",
         "best_used_for": "Mastering, mix bus"},
        {"name": "ReaGate", "developer": "Cockos", "category": "Gate", "subcategory": "Noise Gate",
         "plugin_type": "effect", "character": "Standard gate with sidechain",
         "best_used_for": "Drum cleanup"},
        {"name": "ReaLimit", "developer": "Cockos", "category": "Limiter", "subcategory": "Brickwall Limiter",
         "plugin_type": "effect", "character": "Peak limiter",
         "best_used_for": "Master bus"},
        {"name": "ReaFir", "developer": "Cockos", "category": "EQ", "subcategory": "FFT EQ / Noise Reduction",
         "plugin_type": "effect", "character": "FFT-based EQ, gate, compressor, subtractor",
         "best_used_for": "Noise reduction, surgical EQ"},
        {"name": "ReaVerbate", "developer": "Cockos", "category": "Reverb", "subcategory": "Algorithmic Reverb",
         "plugin_type": "effect", "character": "Simple algorithmic reverb",
         "best_used_for": "CPU-light reverb"},
        {"name": "ReaVerb", "developer": "Cockos", "category": "Reverb", "subcategory": "Convolution Reverb",
         "plugin_type": "effect", "character": "Convolution engine",
         "best_used_for": "Realistic spaces with external IRs"},
        {"name": "ReaDelay", "developer": "Cockos", "category": "Delay", "subcategory": "Multi-tap Delay",
         "plugin_type": "effect", "character": "Multi-tap delay",
         "best_used_for": "Flexible delay structures"},
        {"name": "ReaPitch", "developer": "Cockos", "category": "Pitch Shifter", "subcategory": "Pitch Shifter",
         "plugin_type": "effect", "character": "Real-time pitch shifting",
         "best_used_for": "Formant shift, harmonization"},
        {"name": "ReaTune", "developer": "Cockos", "category": "Pitch Correction", "subcategory": "Auto-Tune Style",
         "plugin_type": "effect", "character": "Pitch correction",
         "best_used_for": "Vocal tuning"},
        {"name": "ReaVocode", "developer": "Cockos", "category": "Vocoder", "subcategory": "Vocoder",
         "plugin_type": "effect", "character": "FFT vocoder",
         "best_used_for": "Robot voices, talking synths"},
        {"name": "ReaSynth", "developer": "Cockos", "category": "Synth", "subcategory": "Basic Synth",
         "plugin_type": "instrument", "character": "Simple built-in synth",
         "best_used_for": "Quick test tones, basic sounds"},
        {"name": "ReaSamplOmatic5000", "developer": "Cockos", "category": "Sampler", "subcategory": "Simple Sampler",
         "plugin_type": "instrument", "character": "One-shot sampler",
         "best_used_for": "Quick sampling tasks"},
        {"name": "ReaControlMIDI", "developer": "Cockos", "category": "MIDI Utility", "subcategory": "MIDI Utility",
         "plugin_type": "effect", "character": "MIDI CC generator",
         "best_used_for": "MIDI control automation"},
        {"name": "ReaInsert", "developer": "Cockos", "category": "Utility", "subcategory": "External Hardware Insert",
         "plugin_type": "effect", "character": "Hardware insert with latency compensation",
         "best_used_for": "Using outboard hardware"},
        {"name": "ReaSurround", "developer": "Cockos", "category": "Utility", "subcategory": "Surround Panner",
         "plugin_type": "effect", "character": "Surround/3D panner",
         "best_used_for": "Surround mixing"},
        {"name": "ReaJS", "developer": "Cockos", "category": "Utility", "subcategory": "Scriptable FX",
         "plugin_type": "effect", "character": "Host for JSFX community scripts",
         "best_used_for": "Custom or community effects"},
    ],

    "GarageBand": [
        # Subset shared with Logic (cross-ref via Apple AU)
        {"name": "Channel EQ", "developer": "Apple", "category": "EQ", "subcategory": "Parametric EQ",
         "plugin_type": "effect", "character": "8-band parametric (shared with Logic)",
         "best_used_for": "Everyday mixing"},
        {"name": "Compressor", "developer": "Apple", "category": "Compressor", "subcategory": "Multi-model",
         "plugin_type": "effect", "character": "Multi-circuit compressor (shared with Logic)",
         "best_used_for": "General compression"},
        {"name": "Space Designer", "developer": "Apple", "category": "Reverb", "subcategory": "Convolution Reverb",
         "plugin_type": "effect", "character": "Convolution reverb (shared with Logic)",
         "best_used_for": "Realistic spaces"},
        {"name": "Echo", "developer": "Apple", "category": "Delay", "subcategory": "Digital Delay",
         "plugin_type": "effect", "character": "Tempo-synced delay",
         "best_used_for": "Everyday delay"},
        {"name": "Amp Designer", "developer": "Apple", "category": "Amp Simulator", "subcategory": "Guitar Amp",
         "plugin_type": "effect", "character": "Guitar amp models",
         "best_used_for": "Guitar tones"},
        {"name": "Pedalboard", "developer": "Apple", "category": "Multi-FX", "subcategory": "Guitar Pedal Chain",
         "plugin_type": "effect", "character": "Stompbox chain",
         "best_used_for": "Guitar tones"},
        {"name": "Drummer", "developer": "Apple", "category": "Drum Machine", "subcategory": "Virtual Drummer",
         "plugin_type": "instrument", "character": "AI-style virtual drummer",
         "best_used_for": "Drum tracks without programming"},
        {"name": "Quick Sampler", "developer": "Apple", "category": "Sampler", "subcategory": "Quick Sampler",
         "plugin_type": "instrument", "character": "Drag-and-drop sampler",
         "best_used_for": "Quick sampling"},
    ],
}


def get_stock_plugins_for(daws: list[str]) -> list[dict]:
    """
    Return a flat list of stock plugins for the given DAWs.

    Each entry is tagged with `_daw` (source DAW) and `_is_stock=True`
    so downstream code (chat context builder) can label it correctly.
    """
    out = []
    for daw in daws:
        for p in DAW_STOCK_PLUGINS.get(daw, []):
            out.append({**p, "_daw": daw, "_is_stock": True})
    return out
